/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\shuttle.glb 
Author: Giimann (https://sketchfab.com/giimann)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-shuttle-002-fba0dcfc79e846d3a7b1e0e0bf7438b0
Title: Space Shuttle 002
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/shuttle.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="a2e4c022d0704409b9254b3288e371d3fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="d1" position={[-3819.654, -1615.987, -9225.197]}>
                  <group name="Object_40" position={[1614.425, 2292.872, 0]}>
                    <mesh name="d1_01_-_Default_0" geometry={nodes['d1_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                  </group>
                </group>
                <group name="d2" position={[4011.838, -1614.22, -9225.197]}>
                  <group name="Object_62" position={[-6217.067, 2291.105, 0]}>
                    <mesh name="d2_01_-_Default_0" geometry={nodes['d2_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                  </group>
                </group>
                <group name="Circle12" position={[3669.495, -7572.643, 0]} />
                <group name="OilTank01" position={[1.286, -2155.444, 634.111]}>
                  <mesh name="OilTank01_17_-_Default_0" geometry={nodes['OilTank01_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Loft01" position={[0, -3151.875, 8880.611]} rotation={[0, -1.571, 0]}>
                  <mesh name="Loft01_17_-_Default_0" geometry={nodes['Loft01_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Cylinder13" position={[-51.336, -4208.665, 17404.809]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Cylinder13_17_-_Default_0" geometry={nodes['Cylinder13_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Box10" position={[92.81, -6340.654, -5942.553]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Box10_17_-_Default_0" geometry={nodes['Box10_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Cylinder12" position={[-1014.992, -2012.743, -3593.002]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Cylinder12_17_-_Default_0" geometry={nodes['Cylinder12_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Loft02" position={[-19.404, -2709.546, -5546.373]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Loft02_17_-_Default_0" geometry={nodes['Loft02_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Loft03" position={[-1907.012, -2709.546, -5669.047]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Loft03_17_-_Default_0" geometry={nodes['Loft03_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Loft04" position={[2087.832, -2709.546, -5923.278]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Loft04_17_-_Default_0" geometry={nodes['Loft04_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Loft05" position={[1992.858, -2709.546, -5975.614]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Loft05_17_-_Default_0" geometry={nodes['Loft05_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Loft06" position={[0, -3450.179, -1488.425]} rotation={[0, -1.571, 0]}>
                  <mesh name="Loft06_17_-_Default_0" geometry={nodes['Loft06_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Cylinder14" position={[-7.122, -4228.367, 10754.495]}>
                  <mesh name="Cylinder14_17_-_Default_0" geometry={nodes['Cylinder14_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Cylinder15" position={[2362.412, -3243.191, 15684.412]} rotation={[-Math.PI / 2, 0, 0.177]}>
                  <group name="Cylinder16" position={[0.679, 23.707, 1063.787]} rotation={[-1.199, 0, -Math.PI]}>
                    <group name="Cylinder53" position={[-0.004, 6.299, 9685.655]} rotation={[0.43, 0, 0]}>
                      <group name="Cylinder54" position={[-10.426, -3.299, 9875.941]} rotation={[0, 0, -Math.PI / 2]}>
                        <mesh name="Cylinder54_17_-_Default_0" geometry={nodes['Cylinder54_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                      </group>
                      <mesh name="Cylinder53_17_-_Default_0" geometry={nodes['Cylinder53_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                    </group>
                    <mesh name="Cylinder16_17_-_Default_0" geometry={nodes['Cylinder16_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                  </group>
                  <mesh name="Cylinder15_17_-_Default_0" geometry={nodes['Cylinder15_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Box11" position={[2350.845, -6212.211, 15668.918]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Box11_17_-_Default_0" geometry={nodes['Box11_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Box05" position={[95.699, -3866.395, -15376.795]} rotation={[Math.PI, 0, -Math.PI]}>
                  <mesh name="Box05_07_-_Default_0" geometry={nodes['Box05_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                </group>
                <group name="Box02" position={[81.862, -1616.745, -13139.881]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Box02_01_-_Default_0" geometry={nodes['Box02_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                </group>
                <group name="Line01" position={[2027.322, -4219.025, -17847.359]} rotation={[0, -1.571, 0]}>
                  <mesh name="Line01_02_-_Default_0" geometry={nodes['Line01_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
                </group>
                <group name="Line11" position={[-1869.661, -4219.025, -17847.359]} rotation={[0, -1.571, 0]}>
                  <mesh name="Line11_02_-_Default_0" geometry={nodes['Line11_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
                </group>
                <group name="Line12" position={[87.475, -109.235, -17221.049]} rotation={[0, -1.571, 0]}>
                  <mesh name="Line12_02_-_Default_0" geometry={nodes['Line12_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
                </group>
                <group name="Box03" position={[155.643, 1657.596, -12451.451]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Box03_09_-_Default_0" geometry={nodes['Box03_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                  <mesh name="Box03_01_-_Default_0" geometry={nodes['Box03_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                </group>
                <group name="Line13" position={[3492.275, 1495.831, -18257.625]} rotation={[0, -1.571, 0]}>
                  <mesh name="Line13_02_-_Default_0" geometry={nodes['Line13_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
                </group>
                <group name="Line14" position={[-3102.677, 1495.831, -18257.625]} rotation={[0, -1.571, 0]}>
                  <mesh name="Line14_02_-_Default_0" geometry={nodes['Line14_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
                </group>
                <group name="Circle04" position={[90.601, -1642.417, 17967.881]} rotation={[Math.PI, 0, Math.PI]}>
                  <mesh name="Circle04_09_-_Default_0" geometry={nodes['Circle04_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                </group>
                <group name="Box06" position={[81.862, -1616.745, -13139.881]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Box06_01_-_Default_0" geometry={nodes['Box06_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                </group>
                <group name="Cylinder01" position={[-3847.713, -1610.744, -2452.229]}>
                  <mesh name="Cylinder01_09_-_Default_0" geometry={nodes['Cylinder01_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                </group>
                <group name="Cylinder02" position={[4096.517, -1610.744, -2452.229]}>
                  <mesh name="Cylinder02_09_-_Default_0" geometry={nodes['Cylinder02_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                </group>
                <group name="tie" position={[90.602, -1642.415, -9234.563]}>
                  <mesh name="tie_09_-_Default_0" geometry={nodes['tie_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                </group>
                <group name="Shape02" position={[-0.239, -6527.298, 0.478]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Shape02_08_-_Default_0" geometry={nodes['Shape02_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
                </group>
                <group name="Cylinder11" position={[437.526, 11521.938, -20215.486]} rotation={[-2.171, 0, 0]}>
                  <mesh name="Cylinder11_01_-_Default_0" geometry={nodes['Cylinder11_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                </group>
                <group name="Box01" position={[-0.239, -6527.298, 0.478]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Box01_01_-_Default_0" geometry={nodes['Box01_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                  <mesh name="Box01_09_-_Default_0" geometry={nodes['Box01_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                  <mesh name="Box01_01_-_Default3_0" geometry={nodes['Box01_01_-_Default3_0'].geometry} material={materials['01_-_Default3']} />
                  <mesh name="Box01_01_-_Default1_0" geometry={nodes['Box01_01_-_Default1_0'].geometry} material={materials['01_-_Default1']} />
                  <mesh name="Box01_03_-_Default_0" geometry={nodes['Box01_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
                  <mesh name="Box01_01_-_Default2_0" geometry={nodes['Box01_01_-_Default2_0'].geometry} material={materials['01_-_Default2']} />
                </group>
                <group name="Shape01" position={[-0.239, -6527.298, 0.478]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Shape01_08_-_Default_0" geometry={nodes['Shape01_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
                </group>
                <group name="Rectangle01" position={[139.962, -13657.82, 21752.93]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_84" position={[206.183, 3632.986, 0]}>
                    <mesh name="Rectangle01_18_-_Default_0" geometry={nodes['Rectangle01_18_-_Default_0'].geometry} material={materials['18_-_Default']} />
                    <mesh name="Rectangle01_05_-_Default_0" geometry={nodes['Rectangle01_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
                    <mesh name="Rectangle01_05_-_Defaultt_0" geometry={nodes['Rectangle01_05_-_Defaultt_0'].geometry} material={materials['05_-_Defaultt']} />
                  </group>
                </group>
                <group name="Circle03" position={[124.327, -13655.824, -8072.494]}>
                  <mesh name="Circle03_05_-_Default_0" geometry={nodes['Circle03_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
                </group>
                <group name="Circle05" position={[124.327, -13655.824, 167.297]}>
                  <mesh name="Circle05_05_-_Default_0" geometry={nodes['Circle05_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
                </group>
                <group name="Circle06" position={[124.326, -13655.824, 8407.088]}>
                  <mesh name="Circle06_05_-_Default_0" geometry={nodes['Circle06_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
                </group>
                <group name="Circle07" position={[124.326, -13655.824, 16646.879]}>
                  <mesh name="Circle07_05_-_Default_0" geometry={nodes['Circle07_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
                </group>
                <group name="Circle08" position={[124.326, -13655.824, 24886.672]}>
                  <mesh name="Circle08_05_-_Default_0" geometry={nodes['Circle08_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
                </group>
                <group name="Circle09" position={[124.325, -13655.824, 33126.461]}>
                  <mesh name="Circle09_05_-_Default_0" geometry={nodes['Circle09_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
                </group>
                <group name="Circle10" position={[124.325, -13655.824, 41366.25]}>
                  <mesh name="Circle10_05_-_Default_0" geometry={nodes['Circle10_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
                </group>
                <group name="Circle11" position={[124.325, -13655.824, 43523.07]}>
                  <mesh name="Circle11_05_-_Default_0" geometry={nodes['Circle11_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
                </group>
                <group name="Line10" position={[139.964, -7822.904, 33360.074]}>
                  <mesh name="Line10_05_-_Defaultt_0" geometry={nodes['Line10_05_-_Defaultt_0'].geometry} material={materials['05_-_Defaultt']} />
                </group>
                <group name="ChamferCyl01" position={[-2444.893, -7943.44, -3742.391]}>
                  <mesh name="ChamferCyl01_05_-_Defaultt_0" geometry={nodes['ChamferCyl01_05_-_Defaultt_0'].geometry} material={materials['05_-_Defaultt']} />
                </group>
                <group name="Line19" position={[236.075, -10386.389, 48304.801]} rotation={[0, -1.571, 0]}>
                  <mesh name="Line19_12_-_Default_0" geometry={nodes['Line19_12_-_Default_0'].geometry} material={materials['12_-_Default']} />
                </group>
                <group name="Line45" position={[166.869, -10386.389, 48304.801]} rotation={[0, -1.571, 0]}>
                  <mesh name="Line45_12_-_Default_0" geometry={nodes['Line45_12_-_Default_0'].geometry} material={materials['12_-_Default']} />
                </group>
                <group name="Line46" position={[-12.628, -10386.389, 48304.801]} rotation={[0, -1.571, 0]}>
                  <mesh name="Line46_12_-_Default_0" geometry={nodes['Line46_12_-_Default_0'].geometry} material={materials['12_-_Default']} />
                </group>
                <group name="Line20" position={[221.67, -13174.715, 58452.051]} rotation={[0, -1.571, 0]}>
                  <mesh name="Line20_05_-_Defaultt_0" geometry={nodes['Line20_05_-_Defaultt_0'].geometry} material={materials['05_-_Defaultt']} />
                </group>
                <group name="Cylinder17" position={[2984.947, -9439.582, -5807.535]} rotation={[-Math.PI / 2, -0.637, 0]}>
                  <mesh name="Cylinder17_05_-_Defaultt_0" geometry={nodes['Cylinder17_05_-_Defaultt_0'].geometry} material={materials['05_-_Defaultt']} />
                </group>
                <group name="Cylinder55" position={[2984.946, -9159.955, 24460.508]} rotation={[-1.681, -0.637, 0]}>
                  <mesh name="Cylinder55_05_-_Defaultt_0" geometry={nodes['Cylinder55_05_-_Defaultt_0'].geometry} material={materials['05_-_Defaultt']} />
                </group>
                <group name="Loft07" position={[2650.906, -8633.344, -4323.795]} rotation={[0, -1.571, 0]}>
                  <mesh name="Loft07_05_-_Defaultt_0" geometry={nodes['Loft07_05_-_Defaultt_0'].geometry} material={materials['05_-_Defaultt']} />
                </group>
                <group name="Loft08" position={[-2280.07, -8633.344, -4323.795]} rotation={[0, -1.571, 0]}>
                  <mesh name="Loft08_05_-_Defaultt_0" geometry={nodes['Loft08_05_-_Defaultt_0'].geometry} material={materials['05_-_Defaultt']} />
                </group>
                <group name="Circle14" position={[-2444.33, -7944.541, 0]} rotation={[0, 0, 0.447]}>
                  <mesh name="Circle14_17_-_Default_0" geometry={nodes['Circle14_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Cylinder57" position={[-7061.482, -13730.256, -6822.336]} rotation={[0, -1.571, 0]}>
                  <mesh name="Cylinder57_21_-_Default_0" geometry={nodes['Cylinder57_21_-_Default_0'].geometry} material={materials['21_-_Default']} />
                </group>
                <group name="Object01" position={[-10018.907, -13788.75, 5953.665]} rotation={[0, -1.571, 0]}>
                  <mesh name="Object01_20_-_Default_0" geometry={nodes['Object01_20_-_Default_0'].geometry} material={materials['20_-_Default']} />
                  <mesh name="Object01_Material_#60_0" geometry={nodes['Object01_Material_#60_0'].geometry} material={materials.Material_60} />
                  <mesh name="Object01_Material_#70_0" geometry={nodes['Object01_Material_#70_0'].geometry} material={materials.Material_70} />
                  <mesh name="Object01_21_-_Default_0" geometry={nodes['Object01_21_-_Default_0'].geometry} material={materials['21_-_Default']} />
                  <mesh name="Object01_20_-_Default_0_1" geometry={nodes['Object01_20_-_Default_0_1'].geometry} material={materials['20_-_Default_0']} />
                  <mesh name="Object01_05_-_Defaultt_0" geometry={nodes['Object01_05_-_Defaultt_0'].geometry} material={materials['05_-_Defaultt']} />
                  <mesh name="Object01_17_-_Default_0" geometry={nodes['Object01_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
                <group name="Object03" position={[-7366.106, -13730.256, -6822.336]} rotation={[0, -1.571, 0]}>
                  <mesh name="Object03_21_-_Default_0" geometry={nodes['Object03_21_-_Default_0'].geometry} material={materials['21_-_Default']} />
                </group>
                <group name="Object02" position={[10345.104, -13788.75, 5953.665]} rotation={[0, -1.571, 0]}>
                  <mesh name="Object02_20_-_Default_0" geometry={nodes['Object02_20_-_Default_0'].geometry} material={materials['20_-_Default']} />
                  <mesh name="Object02_Material_#60_0" geometry={nodes['Object02_Material_#60_0'].geometry} material={materials.Material_60} />
                  <mesh name="Object02_Material_#70_0" geometry={nodes['Object02_Material_#70_0'].geometry} material={materials.Material_70} />
                  <mesh name="Object02_21_-_Default_0" geometry={nodes['Object02_21_-_Default_0'].geometry} material={materials['21_-_Default']} />
                  <mesh name="Object02_20_-_Default_0_1" geometry={nodes['Object02_20_-_Default_0_1'].geometry} material={materials['20_-_Default_1']} />
                  <mesh name="Object02_05_-_Defaultt_0" geometry={nodes['Object02_05_-_Defaultt_0'].geometry} material={materials['05_-_Defaultt']} />
                  <mesh name="Object02_17_-_Default_0" geometry={nodes['Object02_17_-_Default_0'].geometry} material={materials['17_-_Default']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shuttle.glb')
