/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 need_some_space.glb Space.jsx 
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { a } from "@react-spring/three";
import spaceScene from "../assets/3d/need_some_space.glb";
import { useFrame, useThree } from "@react-three/fiber";

const Space = (props) => {
  const { gl, viewport } = useThree();
  const spaceRef = useRef();
  const { nodes, materials, animations, scene } = useGLTF(spaceScene);
  const { actions } = useAnimations(animations, spaceRef);
  return (
    <a.group ref={spaceRef} {...props} dispose={null}>
      <points
        geometry={nodes.Object_2.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.013}
      />
    </a.group>
  );
};

export default Space;
