/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\ufo.glb 
Author: Duznot (https://sketchfab.com/duz_vr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ufo-f8a9a4260e2f4576a8214af5e7c64885
Title: UFO
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ufo.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Spaceship_bakedfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Saucer" position={[0, 120.428, 0]} rotation={[-Math.PI / 2, 0.001, 0]} scale={100}>
                  <mesh name="0" geometry={nodes['0'].geometry} material={materials.Saucer} />
                  <mesh name="1" geometry={nodes['1'].geometry} material={materials.Glass} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ufo.glb')
